# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

baseURL = "https://code-chimp.com"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30
timeout = 60000

buildDrafts = false
buildFuture = false

googleAnalytics = "G-MSLCX3JM5M"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
